function [B,elapse] = AGH1_compress(A, model)
%   This is a wrapper function of One Layer AGH (Anchor Graph Hashing) testing.
%
%	Usage:
%	[B,elapse] = AGH1_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by CPH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%   version 2.0 --Nov/2016 
%   version 1.0 --Jan/2014 
%
%   Written by  Yue Lin (linyue29@gmail.com)
%               Deng Cai (dengcai AT gmail DOT com) 
%                                   

tmp_T = tic;

B = OneLayerAGH_Test(A, model.Anchor, model.W, model.s, model.sigma, model.options);

elapse = toc(tmp_T);
end
