function [B,elapse] = KLSH_compress(A, model)
%   This is a wrapper function of Kernelized LSH testing.
%   The  KLSH TPAMI did not mension how to constrct the kernel. We follow
%   the method in Complmentary Projection Hashing ICCV 2013.
%
%	Usage:
%	[B,elapse] = KLSH_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by KLSH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%   version 2.0 --Nov/2016 
%   version 1.0 --Jan/2012 
%
%   Written by  Yue Lin (linyue29@gmail.com)
%               Deng Cai (dengcai AT gmail DOT com) 
%                                             
tmp_T = tic;

options.KernelType = 'Gaussian';
options.t = model.t;
KTest = constructKernel(A, model.Landmarks, options);
Ym = KTest * model.U;
B = (Ym > 0);

elapse = toc(tmp_T);

end

