function [B,elapse] = LSH_compress(A, model)
%   This is a wrapper function of LSH (Locality Sensitive Hashing)  testing.
%
%	Usage:
%	[B,elapse] = LSH_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by LSH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%   version 2.0 --Nov/2016 
%   version 1.0 --Jan/2011 
%
%   Written by  Yue Lin (linyue29@gmail.com)
%               Deng Cai (dengcai AT gmail DOT com) 
%                                             


tmp_T = tic;

Ym = A * model.U;
B = (Ym > 0);

elapse = toc(tmp_T);
end
