function [B, elapse] = SH_compress(A, model)
%   This is a wrapper function of Spectral Hashing testing.
%
%	Usage:
%	[B,elapse] = SH_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by SH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%   version 2.0 --Dec/2016 
%   version 1.0 --Jan/2013 
%
%   Written by  Yue Lin (linyue29@gmail.com)
%               Deng Cai (dengcai AT gmail DOT com) 
%                                             

tmp_T = tic;

Nsamples = size(A,1);
maxbits = size(model.pc,2);

A = A*model.pc;

A = A-repmat(model.mn, [Nsamples 1]);
omega0=pi./(model.mx-model.mn);
omegas=model.modes.*repmat(omega0, [maxbits 1]);

U = zeros([Nsamples maxbits]);
for i=1:maxbits
    omegai = repmat(omegas(i,:), [Nsamples 1]);
    ys = sin(A.*omegai+pi/2);
    yi = prod(ys,2);
    U(:,i)=yi;    
end

B = (U>0);

elapse = toc(tmp_T);

end
