function [B,elapse] = SpH_compress(A, model)
%   This is a wrapper function of Spherical Hashing testing.
%
%	Usage:
%	[B,elapse] = SpH_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by SpH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%   version 2.0 --Nov/2016 
%   version 1.0 --Jan/2013 
%
%   Written by  Zhongming Jin (jinzhongming888@gmail.com)
%               Deng Cai (dengcai AT gmail DOT com) 
%                                             

tmp_T = tic;

D = EuDist2(A, model.centers);
radii = model.radii';
B = (D > repmat(radii, size(A,1), 1));

elapse = toc(tmp_T);
end
